 developer1method():
    print('Shokhrukh')
    print('Davlatmamadov')
    print('shodavlat21@gmail.com')
    print('Freshman')
    print('19')
 developer2method():
    pass
 developer3method():
    pass